### ISSUE TITLE
Advice about userland indexmap wrapper for clustered inputs

### ISSUE THREAD

**Issue by Yomguithereal** [indexmap-rs/indexmap#356]
Sorry about the fuzzy issue name but I currently use `indexmap` to create on my end a custom hashmap-like structure able to minimize the number of lookups when the data comes sorted or mostly sorted (in chunks often). Thinks of a table with a column used as key and another as value, and rows where it is frequent to have the same key repeated multiple times before changing.

Since `indexmap` stores a dense vector of entries and can swap indices in constant time, I use it to check if the last entry has the same key as what I want to insert before even trying to insert normally through a hashmap lookup. And, if the hashmap lookup gets an occupied entry, I swap it to put it in last position so that next insert with the same key can forego said lookup.

This niche hashmap can very well be developed from userland and you can find one here: https://github.com/medialab/xan/blob/master/src/collections/clustered_insert_hashmap.rs

Where I struggle though is to expose some kind of entry interface to my users. I can very well work with callback-based methods as demonstrated here: https://github.com/medialab/xan/blob/master/src/collections/clustered_insert_hashmap.rs#L78-L115 but they have their issues as well and I would love to be able to expose some kind of entry system. But I need to be able to work both with `indexmap::map::Entry` and `indexmap::map::IndexedEntry`, as well as swapping an occupied entry for the user if relevant, but I cannot make it work because the borrow checker does not let me or because entry methods swapping indices takes ownership of the entry and I cannot return it to the user afterwards. I cannot either use a DropGuard because I cannot access the mutable reference to the map from the entry, from userland at least.

So I was wondering if you would have some advice, or if there is something obvious I could contribute here.

**Comment by cuviper** [comment]
> but I cannot make it work because the borrow checker does not let me or because entry methods swapping indices takes ownership of the entry and I cannot return it to the user afterwards.

Can you give a more complete example of what you would like to be able to do here?

My initial though is that locally, you could get an entry, save its index, and perform the swap, and then construct a new `IndexedEntry` (which is cheap) for passing back to the user. There's also `From` between that and `OccupiedEntry` in both directions, and while it does require a hash table lookup to convert to occupied, that's a simple index comparison rather than a full hash/eq lookup.

**Comment by cuviper** [comment]
> Notice how the match in the `entry` method cannot build and IndexedEntry in the occupied branch because `self.map` is already mutably borrowed. This branch cannot return the occupied entry neither because the `swap_indices` methods takes ownership of the entry and return nothing.

This is sadly a limitation of the current borrow checker, but it *does* work under nightly `-Zpolonius` -- see:
https://blog.rust-lang.org/inside-rust/2023/10/06/polonius-update.html

The typical workaround is to write it with borrow-independent branches, something like:

```rust
    pub fn entry(&mut self, key: K) -> Entry<K, V> {
        let len = self.map.len();
        if let Some(i) = self.map.get_index_of(&key) {
            self.map.swap_indices(i, len - 1);
            Entry::Indexed(self.map.get_index_entry(len - 1).unwrap())
        } else {
            match self.map.entry(key) {
                IndexMapEntry::Vacant(entry) => Entry::Vacant(entry),
                IndexMapEntry::Occupied(_) => unreachable!(),
            }
        }
    }
```

You could probably use the [raw entry API](https://docs.rs/indexmap/latest/indexmap/map/trait.RawEntryApiV1.html) to avoid the rehashing cost in that vacant branch as well, e.g. hash it yourself, use [`index_from_hash`](https://docs.rs/indexmap/latest/indexmap/map/raw_entry_v1/struct.RawEntryBuilder.html#method.index_from_hash) instead of `get_index_of`, and then [`from_key_hashed_nocheck`](https://docs.rs/indexmap/latest/indexmap/map/raw_entry_v1/struct.RawEntryBuilderMut.html#method.from_key_hashed_nocheck) to get a (raw) vacant entry.

**Comment by Yomguithereal** [comment]
Thanks for the information and tips @cuviper. I will try something in this vein. Truth be told, I am not sure I need the case where the vacant entry is not inserted, but it is still an interesting case. Is there a rationale behind the fact that the `entry.swap_indices` method needs to take ownership, rather that mutating? I guess it would be hard to maintain correct the state of the entry itself? In any case, I will now close this issue, thanks :)

**Comment by cuviper** [comment]
> Is there a rationale behind the fact that the `entry.swap_indices` method needs to take ownership, rather that mutating? I guess it would be hard to maintain correct the state of the entry itself?

Right, we would similarly have to reconstruct the entry after performing the swap.
