### ISSUE TITLE
hashbrown 0.15.1 requires Rust 1.65 which breaks 1.63 MSRV here

### ISSUE THREAD

**Issue by eaufavor** [indexmap-rs/indexmap#358]
https://github.com/rust-lang/hashbrown/issues/585

**Comment by cuviper** [comment]
I'm not going to restrict the _maximum_ semver-compatible dependency version, and this is otherwise inactionable on `indexmap`'s part. When you need to build on 1.63, you can run `cargo update -p hashbrown --precise 0.15.0`. If you have multiple `hashbrown` in your dependency tree, you'll need to disambiguate `hashbrown@0.15.1` that you're "updating".
